version: '3.8'

services:  
  back:
    image: node:18.15.0-alpine3.17
    container_name: challenge2-back
    working_dir: /home/node/app
    tty: true
    stdin_open: true
    env_file: .env
    ports:
      - $BACK_PORT:3000
    volumes:
      - ./:/home/node/app

  db:
    image: postgres:15.2-alpine3.17
    container_name: challenge2_db
    env_file: .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:5432
    volumes:
      - data_db:/var/lib/postgresql/data

volumes:
  data_db:

networks:
  challenge2:
    external: true