apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-deployment
  labels:
    app: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
      - name: elk
        image: elasticsearch:7.14.0
        ports:
        - containerPort: 9200
        env:
          - name: "node.name"
            value: elasticsearch
          - name: "discovery.type"
            value: single-node
---

apiVersion: v1
kind: Service
metadata:
  name: elk
spec:
  selector:
    app: elk
  ports:
    - name: port
      protocol: TCP
      port: 9200
      targetPort: 9200