apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-gateway
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - #{HOST}#
      secretName: #{SECRET_NAME}#
  rules:
  - host: #{HOST}#
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: auth-api
            port:
              number: 3000
      - path: /users/*
        pathType: Prefix
        backend:
          service:
            name: auth-api
            port:
              number: 3000
      # - path: /auth/*
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: auth-api
      #       port:
      #         number: 3000
      
      - path: /applications
        pathType: Prefix
        backend:
          service:
            name: candidate-api
            port:
              number: 3000
      - path: /applications/*
        pathType: Prefix
        backend:
          service:
            name: candidate-api
            port:
              number: 3000
      - path: /bookmarks
        pathType: Prefix
        backend:
          service:
            name: candidate-api
            port:
              number: 3000
      - path: /bookmarks/*
        pathType: Prefix
        backend:
          service:
            name: candidate-api
            port:
              number: 3000
      
      - path: /companies
        pathType: Prefix
        backend:
          service:
            name: recruiter-api
            port:
              number: 3000
      - path: /companies/*
        pathType: Prefix
        backend:
          service:
            name: recruiter-api
            port:
              number: 3000
      - path: /job-offers
        pathType: Prefix
        backend:
          service:
            name: recruiter-api
            port:
              number: 3000
      - path: /job-offers/*
        pathType: Prefix
        backend:
          service:
            name: recruiter-api
            port:
              number: 3000