apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruiter-api-deployment
  labels:
    app: recruiter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruiter-api
  template:
    metadata:
      labels:
        app: recruiter-api
    spec:
      containers:
      - name: recruiter-api
        image:  "#{ACR}#/recruiter-api"
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: recruiter-config
                key: DATABASE_URL
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: recruiter-config
                key: AZURE_STORAGE_CONNECTION_STRING
          - name: AZURE_BLOB_PRIVATE_CONTAINER
            valueFrom:
              configMapKeyRef:
                name: recruiter-config
                key: AZURE_BLOB_PRIVATE_CONTAINER
          - name: AZURE_BLOB_PUBLIC_CONTAINER
            valueFrom:
              configMapKeyRef:
                name: recruiter-config
                key: AZURE_BLOB_PUBLIC_CONTAINER
---

apiVersion: v1
kind: Service
metadata:
  name: recruiter-api
spec:
  selector:
    app: recruiter-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000