apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruiter-api-deployment
  labels:
    app: recruiter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruiter-api
  template:
    metadata:
      labels:
        app: recruiter-api
    spec:
      containers:
      - name: recruiter-api
        image:  "#{ACR}#/recruiter-api"
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: recruiter-api
spec:
  selector:
    app: recruiter-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000