name: CI/CD auth microservice

on:
  push:
    branches:
      - "main"
      - "feat/k8s-config"
    paths:
      - "services/auth-api/**"
      - ".github/workflows/auth-api.yml"
      - "k8s/auth-api.yml"
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./services/auth-api
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: npm install
  #     - name: Run Tests
  #       run: npm test

  publish-image:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:services/auth-api"
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/auth-api:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3
      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}
      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: k8s/auth-api.yml
        env:
          ACR: ${{ secrets.ACR_ENDPOINT }}
      - name: Deploy Manifests
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            k8s/auth-api.yml
      - name: Rollout deployement
        run: kubectl rollout restart deployment auth-api-deployment