name: CI/CD candidate microservice

on:
  push:
    branches:
      - "main"
    paths:
      - "services/candidate-api/**"
      - ".github/workflows/candidate-api.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/candidate-api
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  publish-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:services/candidate-api"
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/candidate-api:latest