name: CI/CD K8s Elasticsearch

on:
  push:
    branches:
      - "main"
      - "feat/k8s-elk"
    paths:
      - ".github/workflows/elk.yml"
      - "k8s/elk.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}
      - name: Deploy Manifests
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/elk.yml