name: CI/CD recruiter microservice

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - "services/recruiter-api/**"
      - ".github/workflows/recruiter-api.yml"
      - "k8s/recruiter-api.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.8-alpine3.17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db_test
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_BLOB_PRIVATE_CONTAINER: ${{ secrets.AZURE_BLOB_PRIVATE_CONTAINER }}
      AZURE_BLOB_PUBLIC_CONTAINER: ${{ secrets.AZURE_BLOB_PUBLIC_CONTAINER}}
      MICROSERVICE_HOST: ${{ secrets.RECRUITER_SERVICE_HOST }}
      MICROSERVICE_PORT: ${{ secrets.MICROSERVICE_PORT }}
      AUTH_SERVICE_HOST: ${{ secrets.AUTH_SERVICE_HOST }}
      AUTH_SERVICE_PORT: ${{ secrets.MICROSERVICE_PORT }}
      CANDIDATE_SERVICE_HOST: ${{ secrets.CANDIDATE_SERVICE_HOST }}
      CANDIDATE_SERVICE_PORT: ${{ secrets.MICROSERVICE_PORT }}
    defaults:
      run:
        working-directory: ./services/recruiter-api
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Migrate DB
        run: npx prisma migrate deploy
      - name: Run e2e tests
        run: npm run test:e2e

  publish-image:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:services/recruiter-api"
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/recruiter-api:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3
      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}
      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: k8s/recruiter-api.yml
        env:
          ACR: ${{ secrets.ACR_ENDPOINT }}
      - name: Deploy Manifests
        uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/recruiter-api.yml
          images: |
            ${{ secrets.ACR_ENDPOINT }}/recruiter-api:${{ github.sha }}